name: on_push

on:
  push:
    branch:
      - "**" # This will run on all branches, and must be quoted to be handled by yaml

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Run tests with maven
        run: mvn  clean verify -Denvironment=qa
      - name: Collect build data
        if: always()
        run: |
          echo "TOTAL_DURATION=$(expr $(date +%s) - ${START_TIME})"
          ./src/test/resources/test-results/test_result_script.sh
      - name: Configure AWS CLI
        run: |
          echo "Here in Configure AWS CLI"
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-north-1
      - name: Upload Serenity Reports to S3
        run: aws s3 cp file:///home/runner/work/test-base-metrics/test-base-metrics/target/site/serenity s3://automation-temp-report/$(date +'%Y%m%d_%H%M%S')/ --recursive

