name: on_push

on:
  push:
    branch:
      - "**" # This will run on all branches, and must be quoted to be handled by yaml

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Run tests with maven
        run: mvn  clean verify -Denvironment=qa